name: Build and push gh-pages
on:
  push:
    paths:
      - 'project/**'
    branches:
      - 'main'
jobs:
  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm test