name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js and npm
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: 'gh-pages'
        folder: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: deploy

    - name: Set deployment URL as output
      run: echo "::set-env name=DEPLOYMENT_URL::${{ env.DEPLOYMENT_URL }}"
      shell: bash

      env:
        DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment_url }}

    - name: Set deployment URL as output
      run: echo "::set-env name=DEPLOYMENT_URL::${{ env.DEPLOYMENT_URL }}"
